name: CI

on:
  push:
    branches: [ cfsMachine ]
  pull_request:
    branches: [ cfsMachine ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull plasmapotential/heat:v3.2

    - name: Run simple CI configuration test test
      run: docker run -v ${{ github.workspace }}:/root/source/HEAT plasmapotential/heat:v3.2 python3 /root/source/HEAT/tests/integrationTests/ciTest.py

    - name: NSTX-U HEAT Calculation
      run: docker run -v ${{ github.workspace }}:/root/source/HEAT plasmapotential/heat:v3.2 /root/source/HEAT/source/runTerminalModeTest


